### ISSUE TITLE
Link to live validator doesn't always work

### ISSUE THREAD

**Issue by cdata** [ucan-wg/ucan-check#32] opened 2022-03-31 19:03 UTC
When I go to https://ucan.xyz/validator directly I get a blank page and this message:

```
ipfs resolve -r /ipns/ucan.xyz/validator: no link named "validator" under bafybeihrv2jlwnqh2ixiikt2ebybci6tg3han2fr7ysd7jwkrs4nzuh2ay
```

This also happens if I use the link on the navigation bar (which gets me to the validator as expected), but then refresh the page.

I'm experiencing this in Chrome Version 98.0.4758.102 (Official Build) (64-bit) on a Debian-based Linux distribution.

**Comment by bgins** [comment] 2022-03-31 20:42
Possible duplicate of #28.

**Comment by bgins** [comment] 2022-03-31 20:46
We may also be able to emit a static build with multiple pages. Our current setup emits a SPA, but the SvelteKit ecosystem has adapters that may be able to provide with an alternative.

**Comment by walkah** [comment] 2022-11-15 21:46
This has been fixed for a while :)

**Closed by walkah** 2022-11-15 21:46 UTC
Labels: bug
